site:
  title: Documentation
  url: http:localhost:5000
content:
  sources: 
  - url: .
    branches: HEAD
    start_paths: [./docs, ./tutorials]
  - url: https://github.com/hazelcast/imdg-docs
    branches: [master, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/imdg-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/management-center-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/management-center-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/hz-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/hazelcast-cloud-code-samples
    branches: master
    start_paths:
    - spring-sample/docs
    - client-failover/client-failover-sample-hazelcast5/docs
  - url: https://github.com/hazelcast-guides/serverless-fraud-detection
    branches: master
    start_paths: docs
  - url: https://github.com/hazelcast-guides/write-through-cache-mongodb-mapstore
    branches: master
    start_paths: docs
  - url: https://github.com/hazelcast-guides/standard-deviation-parallel-processing
    branches: master
    start_paths: docs
  - url: https://github.com/hazelcast/hazelcast-cloud-maven-plugin
    branches: serverless-mvp-uat
    start_path: docs
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/download/v3.1-beta/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true
    idprefix: ''
    idseparator: '-'
    hazelcast-cloud: Viridian
    page-cloud-console: https://viridian.hazelcast.com/
  extensions:
    - ./lib/tabs-block.js
    - asciidoctor-kroki
